Cms:
  namespace:
    0:
      alias: AlphaLemon
      path: /../vendor/bundles
    1:
      alias: AlphaLemonCmsCore
      path: /../vendor/bundles/AlphaLemon/CmsBundle/src
  bundle: 
    class: AlphaLemon\AlphaLemonCmsBundle\AlphaLemonCmsBundle
    environment: 
      0: alcms
      1: alcms_dev
      2: text