framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_rkcms_dev.yml" }
    translator:      { fallback: %locale% }
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

red_kite_cms:
    enable_yui_compressor: true
    active_theme_file: %kernel.root_dir%/Resources/.tests_active_theme